{
  // https://github.com/chriscamicas/abl-tmlanguage
  "scopeName": "source.omni",
  "patterns": [
    // Types
    {
      "match": "\\b(Byte|Short|Integer|Long|Float|Double|String|Char|Boolean|Error)\\b",
      "name": "keyword.type.omni"
    },
    // Keywords
    {
      "match": "\\b(if|else|for|while|is)\\b",
      "name": "keyword.control.omni"
    },
    {
      "match": "\\b(return|break|continue)\\b",
      "name": "keyword.control.flow.omni"
    },
    // Filters
    {
      "match": "@\\w+",
      "name": "entity.name.tag.omni"
    },
    // Static constants
    {
      "match": "\\b(true|false)\\b",
      "name": "constant.boolean.omni"
    },
    {
      "match": "\"(.*?)\"",
      "name": "string.quoted.double.yourlanguage"
    },
    {
      "match": "\\b\\d+(\\.\\d+)?\\b",
      "name": "constant.numeric.yourlanguage"
    }
  ]
}